# Copied and modified from https://github.com/mlcommons/medperf/blob/905e9fdeb33e10beb83307cde9d11040e8a33b0b/.github/workflows/docs-ci.yml
name: docs-ci
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - run: pip install -r docs/requirements.txt
      - run: git config --system core.longpaths true
      - run: mkdocs gh-deploy --force
